name: Portfolio Projects Update

on:
  schedule:
    - cron: "0 0 * * *"

  repository_dispatch:
    types:
      - portfolio_projects_update

  Workflow_dispatch:

  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Run Python Script
        run: |
          cd aryan.me
          pip install -r requirements.txt
          python projects_update.py

      - name: Workflow Completed
        run: |
          echo "Workflow completed!"
